### ISSUE TITLE
numpy.fft.fft2 raises AssertionError

### ISSUE THREAD

**Issue by densmirn** [IntelPython/mkl_fft#64]
Steps to reproduce:
`conda create -n mkl_fft`
`conda activate mkl_fft`
`conda install python=3.8 mkl_fft -c intel`
`python`

```python
>>> import numpy
>>> a = numpy.array([[5, 7, 6, 5], [4, 6, 4, 8], [9, 3, 7, 5]])
>>> b = numpy.fft.fft2(a, None, None, "ortho")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nfs/site/home/denissmi/.conda/envs/mkl_fft/lib/python3.8/site-packages/mkl_fft/_numpy_fft.py", line 1081, in fft2
    return fftn(x, s=s, axes=axes, norm=norm)
  File "/nfs/site/home/denissmi/.conda/envs/mkl_fft/lib/python3.8/site-packages/mkl_fft/_numpy_fft.py", line 859, in fftn
    output = trycall(
  File "/nfs/site/home/denissmi/.conda/envs/mkl_fft/lib/python3.8/site-packages/mkl_fft/_numpy_fft.py", line 98, in trycall
    res = func(*args, **kwrds)
  File "mkl_fft/_pydfti.pyx", line 1105, in mkl_fft._pydfti.fftn
  File "mkl_fft/_pydfti.pyx", line 1083, in mkl_fft._pydfti._fftnd_impl
  File "mkl_fft/_pydfti.pyx", line 930, in mkl_fft._pydfti.iter_complementary
  File "mkl_fft/_pydfti.pyx", line 985, in mkl_fft._pydfti._direct_fftnd
AssertionError
```

**Comment by densmirn** [comment]
`conda list`
```
# packages in environment at /nfs/site/home/denissmi/.conda/envs/mkl_fft:
#
# Name                    Version                   Build  Channel
bzip2                     1.0.8                hb9a14ef_8    intel
ca-certificates           2020.12.5                     0    intel
certifi                   2020.12.5        py38he139614_0    intel
common_cmplr_lib_rt       2021.3.0             intel_3350    intel
common_cmplr_lic_rt       2021.3.0             intel_3350    intel
dpcpp-cpp-rt              2021.3.0             intel_3350    intel
dpcpp_cpp_rt              2021.3.0             intel_3350    intel
icc_rt                    2021.3.0             intel_3350    intel
intel-cmplr-lib-rt        2021.3.0             intel_3350    intel
intel-cmplr-lic-rt        2021.3.0             intel_3350    intel
intel-opencl-rt           2021.3.0             intel_3350    intel
intel-openmp              2021.3.0             intel_3350    intel
intelpython               2021.3.0                      7    intel
libffi                    3.3                          13    intel
libgcc-ng                 9.3.0              hdf63c60_101    intel
mkl                       2021.3.0              intel_520    intel
mkl-service               2.4.0            py38h76adbe5_0    intel
mkl_fft                   1.3.0            py38h6d51d7b_1    intel
numpy-base                1.20.3           py38hf45626f_1    intel
opencl_rt                 2021.3.0             intel_3350    intel
openssl                   1.1.1k               h14c3975_1    intel
pip                       21.1.1           py38ha59826b_0    intel
python                    3.8.11               ha27d850_1    intel
setuptools                52.0.0           py38h0d5a7d4_0    intel
six                       1.16.0           py38h7c2029b_0    intel
sqlite                    3.35.5               hb9a14ef_1    intel
tbb                       2021.3.0              intel_511    intel
tbb4py                    2021.3.0         py38_intel_511    intel
tcl                       8.6.10                        1    intel
tk                        8.6.10               h8e2d9d6_3    intel
wheel                     0.36.2           py38ha11c92b_0    intel
xz                        5.2.5                h74280d8_2    intel
zlib                      1.2.11.1             h047b5d8_3    intel
```

**Comment by oleksandr-pavlyk** [comment]
Coming from  `mkl_fft.fftn`:

```
In [6]: mkl_fft.fftn(a, shape=None, axes=(-2, -1))
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-6-8f64e75547c3> in <module>
----> 1 mkl_fft.fftn(a, shape=None, axes=(-2, -1))

mkl_fft/_pydfti.pyx in mkl_fft._pydfti.fftn()

mkl_fft/_pydfti.pyx in mkl_fft._pydfti._fftnd_impl()

mkl_fft/_pydfti.pyx in mkl_fft._pydfti.iter_complementary()

mkl_fft/_pydfti.pyx in mkl_fft._pydfti._direct_fftnd()

AssertionError:
```
